baseURL = "https://jerryyf.github.io"
languageCode = "en"
theme = "anubis"
title = "linsomnia"
paginate = 3
DefaultContentLanguage = "en"

[author]
  name = "Jerry Lin"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Posts"
    url = "/tags/"
    weight = 3

[params]
  author = "Jerry Lin"
  description = "Not a robot"
  dateFormat = "02-01-2006"
  paginationSinglePost = true
  style = "auto"
  mainSections = [ "posts" ]
  sectionsWithFullContentOnListPage = [ "notes" ]
  readMore = true
  readNextPosts = 5
  disableSummary = false
  toc = true
  tocWordCount = 300
  copyCodeButton = true
  rssAsSocialIcon = false
  mathjax = false

  [[params.social]]
  id = "github"
  url = "https://github.com/jerryyf"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup.goldmark.renderer]
unsafe = true